language: perl
perl:
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   - "5.8"

install:
   # for testing
   - cpanm --notest --metacpan --skip-satisfied --quiet YAML

   # M::I deps
   - cpanm --notest --metacpan --skip-satisfied --quiet Module::Install Module::Install::AuthorRequires Module::Install::CheckConflicts Module::Install::AuthorTests Module::Install::Authority

    #coveralls.io stuff
   - cpanm --notest --metacpan --skip-satisfied --quiet ExtUtils::MakeMaker Devel::Cover::Report::Coveralls

   # author deps -- wish there was a better way
   - cpanm --notest --metacpan --skip-satisfied --quiet CatalystX::LeakChecker Catalyst::Devel Catalyst::Engine::PSGI Starman MooseX::Daemonize Test::WWW::Mechanize::Catalyst Catalyst::Plugin::Params::Nested
   - cpanm --notest --metacpan --skip-satisfied --quiet Test::Without::Module Test::NoTabs Test::Pod Test::Pod::Coverage Test::Spelling Pod::Coverage::TrustPod
   - cpanm --notest --metacpan --skip-satisfied --quiet --installdeps .
   - echo y | perl Makefile.PL

   # enable various test options, including parallel testing
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1

   # we want these for our tests, but not for any others
   - export AUTHOR_TESTING=1
   - export RELEASE_TESTING=1

   - make manifest

   #it's like make disttest, only manual, so we can send a report to coveralls.io
   - make distdir
   - cd $(perl -MCPAN::Meta -e '$m = CPAN::Meta->load_file("MYMETA.yml"); print $m->name . "-" . $m->version')
   - perl Makefile.PL
script:
   - cover -test -report coveralls
